In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
import seaborn as sb

In [6]:
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv('data.csv')

In [16]:
df  = df.drop_duplicates()

In [17]:
df  = df.dropna()

In [20]:
df.describe()

,Fixed Acidity,Volatile Acidity,Citric Acid,Residual Sugar,Chlorides,Free Sulfur Dioxide,Total Sulfur Dioxide,Density,pH,Sulphates,Alcohol,Quality
count,4.000000,4.00000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.0,4.00
mean,8.550000,0.65500,0.150000,2.175000,0.085250,17.000000,53.750000,0.997400,3.282500,0.617500,9.7,5.25
std,1.776701,0.26096,0.273983,0.340343,0.011529,5.887841,14.198005,0.000589,0.157136,0.056789,0.2,0.50
min,7.400000,0.28000,0.000000,1.900000,0.075000,11.000000,34.000000,0.996800,3.160000,0.560000,9.4,5.00
25%,7.700000,0.59500,0.000000,1.900000,0.075750,14.000000,49.000000,0.996950,3.190000,0.575000,9.7,5.00
50%,7.800000,0.73000,0.020000,2.100000,0.084000,16.000000,57.000000,0.997400,3.230000,0.615000,9.8,5.00
75%,8.650000,0.79000,0.170000,2.375000,0.093500,19.000000,61.750000,0.997850,3.322500,0.657500,9.8,5.25
max,11.200000,0.88000,0.560000,2.600000,0.098000,25.000000,67.000000,0.998000,3.510000,0.680000,9.8,6.00

In [26]:
'STATISTICS WITH RESPECT TO COLUMNS'

'STATISTICS WITH RESPECT TO COLUMNS'

In [32]:
df[['Fixed Acidity','Alcohol','Volatile Acidity','Citric Acid','Residual Sugar','Chlorides','Density','pH','Sulphates','Quality']].describe()

,Fixed Acidity,Alcohol,Volatile Acidity,Citric Acid,Residual Sugar,Chlorides,Density,pH,Sulphates,Quality
count,4.000000,4.0,4.00000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.00
mean,8.550000,9.7,0.65500,0.150000,2.175000,0.085250,0.997400,3.282500,0.617500,5.25
std,1.776701,0.2,0.26096,0.273983,0.340343,0.011529,0.000589,0.157136,0.056789,0.50
min,7.400000,9.4,0.28000,0.000000,1.900000,0.075000,0.996800,3.160000,0.560000,5.00
25%,7.700000,9.7,0.59500,0.000000,1.900000,0.075750,0.996950,3.190000,0.575000,5.00
50%,7.800000,9.8,0.73000,0.020000,2.100000,0.084000,0.997400,3.230000,0.615000,5.00
75%,8.650000,9.8,0.79000,0.170000,2.375000,0.093500,0.997850,3.322500,0.657500,5.25
max,11.200000,9.8,0.88000,0.560000,2.600000,0.098000,0.998000,3.510000,0.680000,6.00

In [40]:
'Highest rated wine has alcohol content of',df['Alcohol'].max()

('Highest rated wine has alcohol content of', 9.8)

In [39]:
'Lowest rated wine has alcohol content of',df['Alcohol'].min()

('Lowest rated wine has alcohol content of', 9.4)